### ISSUE TITLE
Can't build Model/apps/miabdtdl2cdmconverter

### ISSUE THREAD

**Issue by JMayrbaeurl** [nimanch/hackformanufacturingdata#10]
I'm getting the following error when trying to compile the project with Visual Studio Code:

'CdmStandardsAdapter' is inaccessible due to its protection level [miabdtdl2cdmconverter] in Program.cs line 54 col 50.

If there's anything special to do to get the project correctly build, please add this to the README.md file.

Thanks
Juergen

**Comment by radheyshah** [comment]
Yes, the reason is that the access modifier 'public' was not set propertly for CdmStandardsAdapter. If you get latest code for CDM adapter, this error would go away. Here is the link to the change that fixed it - https://github.com/microsoft/CDM/blame/90aecb003f08fe98bf37b1cdb40c2d84fac2200d/objectModel/CSharp/Microsoft.CommonDataModel.ObjectModel/Storage/CdmStandardsAdapter.cs#L17
